name: Flutter Web Build

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
